base: &base
  adapter: postgresql
  encoding: utf-8
  pool: 30
  username: dagnisslogis
  database: rails_ajax

development:
  <<: *base

test:
  <<: *base
  database: rails_ajax_test

production:
  <<: *base
